steps:
  - name: "maven"
    args: ["mvn", "--version"] 
    
  - name: 'gcr.io/poc-dna-automation-693335/dbt-bigquery:latest'
    id: 'Download DBT Image'
    args: ["dbt", "--version"] 
  
 
     
  
      
  # DEV - DBT DEBUG
  - name: "python:3.7" 
    id: 'DEV - DBT DEBUG'
    args: ['dbt', 'debug','--target','dev']
  
  # DEV - DBT RUN
  - name: "python:3.7" 
    id: 'DEV - DBT RUN'
    args: ['dbt', 'run','--target','dev']
    env:
    - 'PATH=${_PYTHON_PATH}'
  # Logging
options:
  logging: CLOUD_LOGGING_ONLY
  #completed
  
