steps:
  - name: "maven"
    args: ["mvn", "--version"] 
    
  - name: 'gcr.io/poc-dna-automation-693335/dbt-bigquery:latest'
    id: 'Download DBT Image'
    args: ["dbt", "--version"] 

# DEV - DBT DEBUG
  - name: "gcr.io/poc-dna-automation-693335/dbt-bigquery:latest" 
    id: 'DEV - DBT DEBUG'
    args: ['dbt', 'debug',"--project-dir","/workspace/dbt_project.yml", "--profiles-dir","/workspace/profiles.yml",'--target','dev']

# DEV - DBT RUN
  - name: "gcr.io/poc-dna-automation-693335/dbt-bigquery:latest" 
    id: 'DEV - DBT RUN'
    args: ['dbt', 'run','--target','dev']
    
# Logging
options:
  logging: CLOUD_LOGGING_ONLY
  #completed
  
